# Generated by Django 4.2.16 on 2024-11-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricedisease',
            name='class_label',
            field=models.CharField(default='invalid', max_length=25),
            preserve_default=False,
        ),
    ]
